#!/usr/bin/env python3
import os
import os.path
import urllib.parse
import urllib.request


downloads = {
    'www': [
        'https://www.clemson.edu/_template-assets/1889/fonts/09f52831-e1cf-48be-9c1e-2d1577e420b7.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/1454a71d-cdbb-429c-8092-122f4493e0c7.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/1c164451-034c-41f5-9542-390709016510.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/25f577c3-f32b-4fbf-b684-3e7c1a76d1ea.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/2ed49e17-92ad-4026-9ae6-d20f88f21840.ttf',
        'https://www.clemson.edu/_template-assets/1889/fonts/363fd092-cd55-4bd1-bdc5-cfc9a7057517.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/413d9688-00d4-47c4-bb55-656a0cd396e9.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/59fa12c0-25c9-4c0c-bd1e-32204311d86d.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/7062b4ff-265a-4366-b34f-443ec5cc2dad.ttf',
        'https://www.clemson.edu/_template-assets/1889/fonts/70ac6679-cf48-4a0e-a909-d1e3bb4a1aa9.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/853e2a9b-4057-42a5-ad7e-0762cda0b13c.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/969cd675-2b4c-4baa-ada6-62bb7ace778f.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/bb3aa0a7-2585-4e89-ad82-658fd561751a.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/c4aef0d4-bfcf-4790-acf5-909881f411e8.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/d5ea405c-2180-4ff0-bd51-3e19fb280be4.ttf',
        'https://www.clemson.edu/_template-assets/1889/fonts/e741f29c-bc18-4343-bff3-db2465a0be3e.ttf',

        'https://www.clemson.edu/brand/resources/logos/wordmark-academic/white-purple.png',

        'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js',

        'https://cdn.jsdelivr.net/npm/hls.js@0.14.11/dist/hls.min.js',
        'https://cdn.jsdelivr.net/npm/hls.js@0.14.11/dist/hls.min.js.map',

        'https://cdn.jsdelivr.net/npm/mediaelement@4.2.16/build/mediaelementplayer.min.css',
        'https://cdn.jsdelivr.net/npm/mediaelement@4.2.16/build/mediaelement-and-player.min.js',
    ],
    'upd/www': [
        'https://www.clemson.edu/_template-assets/1889/fonts/09f52831-e1cf-48be-9c1e-2d1577e420b7.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/1454a71d-cdbb-429c-8092-122f4493e0c7.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/1c164451-034c-41f5-9542-390709016510.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/25f577c3-f32b-4fbf-b684-3e7c1a76d1ea.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/2ed49e17-92ad-4026-9ae6-d20f88f21840.ttf',
        'https://www.clemson.edu/_template-assets/1889/fonts/363fd092-cd55-4bd1-bdc5-cfc9a7057517.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/413d9688-00d4-47c4-bb55-656a0cd396e9.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/59fa12c0-25c9-4c0c-bd1e-32204311d86d.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/7062b4ff-265a-4366-b34f-443ec5cc2dad.ttf',
        'https://www.clemson.edu/_template-assets/1889/fonts/70ac6679-cf48-4a0e-a909-d1e3bb4a1aa9.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/853e2a9b-4057-42a5-ad7e-0762cda0b13c.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/969cd675-2b4c-4baa-ada6-62bb7ace778f.svg',
        'https://www.clemson.edu/_template-assets/1889/fonts/bb3aa0a7-2585-4e89-ad82-658fd561751a.eot',
        'https://www.clemson.edu/_template-assets/1889/fonts/c4aef0d4-bfcf-4790-acf5-909881f411e8.woff',
        'https://www.clemson.edu/_template-assets/1889/fonts/d5ea405c-2180-4ff0-bd51-3e19fb280be4.ttf',
        'https://www.clemson.edu/_template-assets/1889/fonts/e741f29c-bc18-4343-bff3-db2465a0be3e.ttf',

        'https://www.clemson.edu/brand/resources/logos/wordmark-academic/white-purple.png',
    ],
}


os.chdir(os.path.dirname(__file__))


for directory, files in downloads.items():
    print('Directory: {}'.format(directory))

    for url in files:
        print('\tURL: {}'.format(url))

        filename = os.path.basename(urllib.parse.urlparse(url).path)

        with urllib.request.urlopen(url) as conn, open(os.path.join(directory, filename), 'wb') as file:
            while True:
                block = conn.read(8192)
                if not block:
                    break
                file.write(block)

    print()
