#!/bin/sh -e
pushd "$(dirname "$(readlink -f "$0")")/www" &>/dev/null

curl -sO https://www.clemson.edu/_template-assets/1889/fonts/09f52831-e1cf-48be-9c1e-2d1577e420b7.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/1454a71d-cdbb-429c-8092-122f4493e0c7.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/1c164451-034c-41f5-9542-390709016510.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/25f577c3-f32b-4fbf-b684-3e7c1a76d1ea.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/2ed49e17-92ad-4026-9ae6-d20f88f21840.ttf
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/363fd092-cd55-4bd1-bdc5-cfc9a7057517.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/413d9688-00d4-47c4-bb55-656a0cd396e9.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/59fa12c0-25c9-4c0c-bd1e-32204311d86d.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/7062b4ff-265a-4366-b34f-443ec5cc2dad.ttf
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/70ac6679-cf48-4a0e-a909-d1e3bb4a1aa9.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/853e2a9b-4057-42a5-ad7e-0762cda0b13c.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/969cd675-2b4c-4baa-ada6-62bb7ace778f.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/bb3aa0a7-2585-4e89-ad82-658fd561751a.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/c4aef0d4-bfcf-4790-acf5-909881f411e8.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/d5ea405c-2180-4ff0-bd51-3e19fb280be4.ttf
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/e741f29c-bc18-4343-bff3-db2465a0be3e.ttf

curl -sO https://www.clemson.edu/brand/resources/logos/wordmark-academic/white-purple.png

popd &>/dev/null
pushd "$(dirname "$(readlink -f "$0")")/upd/www" &>/dev/null

curl -sO https://www.clemson.edu/_template-assets/1889/fonts/09f52831-e1cf-48be-9c1e-2d1577e420b7.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/1454a71d-cdbb-429c-8092-122f4493e0c7.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/1c164451-034c-41f5-9542-390709016510.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/25f577c3-f32b-4fbf-b684-3e7c1a76d1ea.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/2ed49e17-92ad-4026-9ae6-d20f88f21840.ttf
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/363fd092-cd55-4bd1-bdc5-cfc9a7057517.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/413d9688-00d4-47c4-bb55-656a0cd396e9.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/59fa12c0-25c9-4c0c-bd1e-32204311d86d.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/7062b4ff-265a-4366-b34f-443ec5cc2dad.ttf
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/70ac6679-cf48-4a0e-a909-d1e3bb4a1aa9.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/853e2a9b-4057-42a5-ad7e-0762cda0b13c.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/969cd675-2b4c-4baa-ada6-62bb7ace778f.svg
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/bb3aa0a7-2585-4e89-ad82-658fd561751a.eot
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/c4aef0d4-bfcf-4790-acf5-909881f411e8.woff
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/d5ea405c-2180-4ff0-bd51-3e19fb280be4.ttf
curl -sO https://www.clemson.edu/_template-assets/1889/fonts/e741f29c-bc18-4343-bff3-db2465a0be3e.ttf

curl -sO https://www.clemson.edu/brand/resources/logos/wordmark-academic/white-purple.png

popd &>/dev/null
